name: CI/CD workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Perform Google Formatter Check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: OSS Scan
        run: mvn ossindex:audit

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Run Unit Tests
        run: mvn test

      - name: Report Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Build Code and Create Docker Image
        run: mvn clean install docker:build
      
      - name: Tag Docker Image
        run: |
          docker tag dnyanyog.org/directoryser:latest ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}    
          
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest 
